gText_Birch_Welcome::
	.string "...\p"
	.string "Ah. You’re awake.\p"
	.string "Most people scream first.\n"
	.string "Promising.\p"
	.string "I’m PROFESSOR THORN.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "You know what this is.\p"
	.string "If you don’t, this will be\n"
	.string "very difficult.\p"
	.string "$"

gText_Birch_MainSpeech::
	.string "In ABSURDIA, POKéMON are\n"
	.string "everything. Power. Infrastructure.\l"
	.string "Currency, almost.\p"
	.string "You will need one or you will\n"
	.string "not last long here.\p"
	.string "That is not a metaphor.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Who are you, exactly?$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "And your name?$"

gText_Birch_SoItsPlayer::
	.string "{PLAYER}{KUN}.\p"
	.string "I will try to remember that.\n"
	.string "I forget most of them.$"

gText_Birch_YourePlayer::
	.string "Right. {PLAYER}{KUN}.\n"
	.string "Moving to NULLTOWN.\p"
	.string "My condolences.\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Come find me when you arrive.\n"
	.string "I’m in the barn.\p"
	.string "Do not touch anything that\n"
	.string "glows.\p"
	.string "$"
