OldaleTown_House1_MapScripts::
	.byte 0

OldaleTown_House1_EventScript_Woman::
	msgbox OldaleTown_House1_Text_LeftPokemonGoesOutFirst, MSGBOX_NPC
	end

OldaleTown_House1_Text_LeftPokemonGoesOutFirst:
	.string "Fun fact: in a battle, whatever\n"
	.string "POKéMON is first in your party gets\l"
	.string "thrown into combat immediately.\p"
	.string "No consent. No warning.\n"
	.string "Just suddenly fighting for its life.\p"
	.string "So maybe don't put the baby one\n"
	.string "first. Just a thought.$"

