import type { ScriptNode, ScriptEdge, ScriptNodeData } from './types'
import { getSchema } from './node-registry'

/* ── Public API ── */

export interface GenerateResult {
  code: string
  replaced: string[]
  warnings: string[]
}

/**
 * Generate assembly from graph nodes, then surgically merge into an existing
 * scripts.inc — only replacing sections the graph owns. Sections not in the
 * graph are preserved verbatim.
 */
export function generateScript(
  nodes: ScriptNode[],
  edges: ScriptEdge[],
  mapName: string,
  existingInc?: string,
): GenerateResult {
  if (nodes.length === 0) return { code: existingInc || '', replaced: [], warnings: [] }

  const ctx = new CodegenContext(nodes, edges, mapName)
  ctx.generate()
  const freshCode = ctx.output()

  if (!existingInc || !existingInc.trim()) {
    return { code: freshCode, replaced: [], warnings: [] }
  }

  return mergeScripts(existingInc, freshCode, mapName)
}

/* ── Surgical merge ── */

interface Section {
  label: string
  body: string
}

/**
 * Parse an .inc file into sections. A section starts at a label line
 * (word followed by : or ::) and runs until the next label or EOF.
 * We also capture a "preamble" section (anything before the first label)
 * and track text data labels separately.
 */
function parseSections(code: string): { preamble: string; sections: Section[] } {
  const lines = code.split('\n')
  const preambleLines: string[] = []
  const sections: Section[] = []
  let current: { label: string; lines: string[] } | null = null

  for (const line of lines) {
    const labelMatch = line.match(/^(\w+):{1,2}\s*$/)
    if (labelMatch) {
      if (current) {
        sections.push({ label: current.label, body: current.lines.join('\n') })
      }
      current = { label: labelMatch[1], lines: [line] }
    } else if (current) {
      current.lines.push(line)
    } else {
      preambleLines.push(line)
    }
  }
  if (current) {
    sections.push({ label: current.label, body: current.lines.join('\n') })
  }
  const preamble = preambleLines.join('\n')

  return { preamble, sections }
}

/**
 * Collect all labels defined by the graph's generated code, including
 * auto-generated sub-labels and text labels.
 */
function collectGraphLabels(freshCode: string): Set<string> {
  const labels = new Set<string>()
  for (const m of freshCode.matchAll(/^(\w+):{1,2}\s*$/gm)) {
    labels.add(m[1])
  }
  return labels
}

function mergeScripts(
  existingCode: string,
  freshCode: string,
  _mapName: string,
): GenerateResult {
  const existing = parseSections(existingCode)
  const fresh = parseSections(freshCode)
  const graphLabels = collectGraphLabels(freshCode)

  const replaced: string[] = []
  const warnings: string[] = []

  /* Build a map of fresh sections for quick lookup */
  const freshMap = new Map<string, Section>()
  for (const s of fresh.sections) {
    freshMap.set(s.label, s)
  }

  /* Walk existing sections. Replace ones the graph owns, keep others. */
  const resultSections: string[] = []
  const emitted = new Set<string>()

  /* Always keep existing preamble — it contains the _MapScripts header
     with on-frame/on-transition tables that the graph doesn't model */
  if (existing.preamble.trim()) {
    resultSections.push(existing.preamble)
  } else if (fresh.preamble.trim()) {
    resultSections.push(fresh.preamble)
  }

  for (const section of existing.sections) {
    if (graphLabels.has(section.label)) {
      /* This section is owned by the graph — replace it */
      if (!emitted.has(section.label)) {
        const freshSection = freshMap.get(section.label)
        if (freshSection) {
          resultSections.push(freshSection.body)
          emitted.add(section.label)
          replaced.push(section.label)
        }
        /* Also emit any fresh sections that should follow this one
           (sub-labels generated by the graph that don't exist in the
           original file) */
        for (const fs of fresh.sections) {
          if (!emitted.has(fs.label) && graphLabels.has(fs.label)) {
            const existsInOriginal = existing.sections.some((s) => s.label === fs.label)
            if (!existsInOriginal) {
              resultSections.push(fs.body)
              emitted.add(fs.label)
              replaced.push(fs.label)
            }
          }
        }
      }
      /* skip — already emitted or part of a replaced group */
    } else {
      /* Not owned by graph — preserve verbatim */
      resultSections.push(section.body)
      emitted.add(section.label)
    }
  }

  /* Emit any fresh sections not yet emitted (entirely new from graph) */
  for (const fs of fresh.sections) {
    if (!emitted.has(fs.label)) {
      resultSections.push(fs.body)
      emitted.add(fs.label)
      replaced.push(fs.label)
    }
  }

  const code = resultSections.join('\n')
  return { code, replaced, warnings }
}

/* ── Internals ── */

class CodegenContext {
  private nodes: ScriptNode[]
  private mapName: string
  private lines: string[] = []
  private textLabels: Map<string, string> = new Map()
  private visited = new Set<string>()
  private labelCounter = 0
  private textCounter = 0

  /* lookup helpers */
  private nodeMap: Map<string, ScriptNode>
  private outEdges: Map<string, ScriptEdge[]>

  constructor(nodes: ScriptNode[], edges: ScriptEdge[], mapName: string) {
    this.nodes = nodes
    this.mapName = mapName
    this.nodeMap = new Map(nodes.map((n) => [n.id, n]))
    this.outEdges = new Map()
    for (const e of edges) {
      const arr = this.outEdges.get(e.source) || []
      arr.push(e)
      this.outEdges.set(e.source, arr)
    }
  }

  generate() {
    /* Do NOT emit _MapScripts header — it contains on-frame/on-transition
       tables that the graph doesn't model. The merge step preserves the
       existing header from the .inc file. */

    /* find all label nodes (entry points) and generate their chains */
    const labelNodes = this.nodes.filter((n) => this.data(n).schemaType === 'label')

    if (labelNodes.length === 0) {
      this.lines.push('@ No script entry points defined')
      return
    }

    for (const labelNode of labelNodes) {
      this.emitChain(labelNode)
      this.lines.push('')
    }

    /* emit text data */
    if (this.textLabels.size > 0) {
      this.lines.push('@ ── Text ──')
      this.lines.push('')
      for (const [label, text] of this.textLabels) {
        this.lines.push(`${label}:`)
        this.emitText(text)
        this.lines.push('')
      }
    }
  }

  output(): string {
    return this.lines.join('\n')
  }

  /* ── Chain walker ── */

  private emitChain(node: ScriptNode) {
    if (this.visited.has(node.id)) return
    this.visited.add(node.id)

    const data = this.data(node)
    const type = data.schemaType

    /* emit label for entry points */
    if (type === 'label') {
      const name = (data.labelName as string) || this.autoLabel()
      this.lines.push(`${name}::`)
    }

    /* emit this node's instructions */
    this.emitNode(node)

    /* follow flow outputs */
    const schema = getSchema(type)
    const outs = this.outEdges.get(node.id) || []

    if (schema.outputs.length === 0) {
      /* terminal node (end, return, warp) — no continuation */
      return
    }

    if (schema.outputs.length === 1) {
      /* linear flow */
      const edge = outs.find((e) => e.sourceHandle === schema.outputs[0].id)
      if (edge) {
        const next = this.nodeMap.get(edge.target)
        if (next) {
          if (this.visited.has(next.id)) {
            /* back-reference: emit goto */
            const targetLabel = this.getLabelForNode(next)
            this.lines.push(`\tgoto ${targetLabel}`)
          } else {
            this.emitChain(next)
          }
        }
      }
      return
    }

    /* branching node: emit branches, then follow each path */
    this.emitBranches(node, outs)
  }

  /* ── Per-node code emission ── */

  private emitNode(node: ScriptNode) {
    const data = this.data(node)
    const type = data.schemaType

    switch (type) {
      case 'label':
        /* label already emitted in emitChain */
        break

      case 'end':
        this.lines.push('\tend')
        break

      case 'return':
        this.lines.push('\treturn')
        break

      case 'call':
        this.lines.push(`\tcall ${data.target || 'MISSING_LABEL'}`)
        break

      case 'msgbox': {
        const textLabel = this.addText(node.id, data.text as string)
        const msgType = data.msgType as string
        this.lines.push(`\tmsgbox ${textLabel}, ${msgType}`)
        break
      }

      case 'branch_flag':
        /* emitted via emitBranches */
        break

      case 'branch_var':
        /* emitted via emitBranches */
        break

      case 'branch_yesno':
        /* emitted via emitBranches */
        break

      case 'set_flag': {
        const action = data.action === 'clear' ? 'clearflag' : 'setflag'
        this.lines.push(`\t${action} ${data.flag || 'FLAG_MISSING'}`)
        break
      }

      case 'set_var':
        this.lines.push(`\tsetvar ${data.var || 'VAR_MISSING'}, ${data.value || '0'}`)
        break

      case 'give_item':
        this.lines.push(`\tgiveitem ${data.item || 'ITEM_MISSING'}, ${data.quantity || '1'}`)
        break

      case 'give_mon': {
        let species = (data.species as string) || 'SPECIES_MISSING'
        if (species !== 'SPECIES_MISSING' && !species.startsWith('SPECIES_')) {
          species = `SPECIES_${species.toUpperCase()}`
        }
        const level = data.level || '5'
        const held = data.item || 'ITEM_NONE'
        this.lines.push(`\tgivemon ${species}, ${level}, ${held}`)
        break
      }

      case 'lock_release': {
        const action = data.action as string
        const scope = data.scope as string
        if (action === 'lock') {
          this.lines.push(scope === 'all' ? '\tlockall' : '\tlock')
        } else {
          this.lines.push(scope === 'all' ? '\treleaseall' : '\trelease')
        }
        break
      }

      case 'faceplayer':
        this.lines.push('\tfaceplayer')
        break

      case 'apply_movement': {
        const obj = data.objectId || 'OBJ_EVENT_ID_PLAYER'
        const mov = data.movementLabel || 'MISSING_MOVEMENT'
        this.lines.push(`\tapplymovement ${obj}, ${mov}`)
        if (data.waitAfter !== false) {
          this.lines.push('\twaitmovement 0')
        }
        break
      }

      case 'trainer_battle': {
        const bt = data.battleType === 'double' ? 'trainerbattle_double' : 'trainerbattle_single'
        const trainer = data.trainer || 'TRAINER_MISSING'
        const introLabel = this.addText(node.id + '_intro', data.introText as string)
        const loseLabel = this.addText(node.id + '_lose', data.loseText as string)
        this.lines.push(`\t${bt} ${trainer}, ${introLabel}, ${loseLabel}`)
        break
      }

      case 'wild_battle': {
        const species = data.species || 'SPECIES_MISSING'
        const level = data.level ?? 5
        const item = (data.item as string) || ''
        if (item && item !== 'ITEM_NONE') {
          this.lines.push(`\tsetwildbattle ${species}, ${level}, ${item}`)
        } else {
          this.lines.push(`\tsetwildbattle ${species}, ${level}`)
        }
        this.lines.push('\tdowildbattle')
        break
      }

      case 'play_sound': {
        const st = data.soundType as string
        const id = data.soundId || 'SE_MISSING'
        if (st === 'se') this.lines.push(`\tplayse ${id}`)
        else if (st === 'fanfare') this.lines.push(`\tplayfanfare ${id}`)
        else this.lines.push(`\tplaybgm ${id}, FALSE`)
        break
      }

      case 'warp': {
        const wt = data.warpType || 'warp'
        const map = data.map || 'MAP_MISSING'
        if (wt === 'warphole') {
          this.lines.push(`\twarphole ${map}`)
        } else {
          this.lines.push(`\t${wt} ${map}, ${data.x || '0'}, ${data.y || '0'}`)
        }
        this.lines.push('\twaitstate')
        break
      }

      case 'delay':
        this.lines.push(`\tdelay ${data.frames || '30'}`)
        break

      case 'special':
        this.lines.push(`\tspecial ${data.func || 'MISSING_FUNC'}`)
        break

      case 'raw_macro':
        if (data.code) {
          for (const line of (data.code as string).split('\n')) {
            this.lines.push(line.startsWith('\t') ? line : `\t${line}`)
          }
        }
        break
    }
  }

  /* ── Branch emission ── */

  private emitBranches(node: ScriptNode, outs: ScriptEdge[]) {
    const data = this.data(node)
    const type = data.schemaType

    if (type === 'branch_flag') {
      const flag = data.flag || 'FLAG_MISSING'
      const trueEdge = outs.find((e) => e.sourceHandle === 'flow_true')
      const falseEdge = outs.find((e) => e.sourceHandle === 'flow_false')

      if (trueEdge) {
        const trueTarget = this.nodeMap.get(trueEdge.target)
        if (trueTarget) {
          const lbl = this.ensureLabel(trueTarget)
          this.lines.push(`\tgoto_if_set ${flag}, ${lbl}`)
        }
      }
      /* fall through to false path */
      if (falseEdge) {
        const falseTarget = this.nodeMap.get(falseEdge.target)
        if (falseTarget && !this.visited.has(falseTarget.id)) {
          this.emitChain(falseTarget)
        }
      }
      /* now emit the true branch */
      if (trueEdge) {
        const trueTarget = this.nodeMap.get(trueEdge.target)
        if (trueTarget && !this.visited.has(trueTarget.id)) {
          this.lines.push('')
          const lbl = this.getLabelForNode(trueTarget)
          this.lines.push(`${lbl}:`)
          this.emitChain(trueTarget)
        }
      }
    } else if (type === 'branch_var') {
      const varName = data.var || 'VAR_RESULT'
      const cmp = data.comparison as string
      const val = data.value || '0'

      const trueEdge = outs.find((e) => e.sourceHandle === 'flow_true')
      const falseEdge = outs.find((e) => e.sourceHandle === 'flow_false')

      this.lines.push(`\tcompare ${varName}, ${val}`)

      const cmpMap: Record<string, string> = {
        '==': 'goto_if_eq',
        '!=': 'goto_if_ne',
        '>': 'goto_if_gt',
        '<': 'goto_if_lt',
        '>=': 'goto_if_ge',
        '<=': 'goto_if_le',
      }

      if (trueEdge) {
        const trueTarget = this.nodeMap.get(trueEdge.target)
        if (trueTarget) {
          const lbl = this.ensureLabel(trueTarget)
          this.lines.push(`\t${cmpMap[cmp] || 'goto_if_eq'} ${lbl}`)
        }
      }

      if (falseEdge) {
        const falseTarget = this.nodeMap.get(falseEdge.target)
        if (falseTarget && !this.visited.has(falseTarget.id)) {
          this.emitChain(falseTarget)
        }
      }

      if (trueEdge) {
        const trueTarget = this.nodeMap.get(trueEdge.target)
        if (trueTarget && !this.visited.has(trueTarget.id)) {
          this.lines.push('')
          const lbl = this.getLabelForNode(trueTarget)
          this.lines.push(`${lbl}:`)
          this.emitChain(trueTarget)
        }
      }
    } else if (type === 'branch_yesno') {
      const yesEdge = outs.find((e) => e.sourceHandle === 'flow_yes')
      const noEdge = outs.find((e) => e.sourceHandle === 'flow_no')

      if (yesEdge) {
        const yesTarget = this.nodeMap.get(yesEdge.target)
        if (yesTarget) {
          const lbl = this.ensureLabel(yesTarget)
          this.lines.push(`\tcompare VAR_RESULT, YES`)
          this.lines.push(`\tgoto_if_eq ${lbl}`)
        }
      }
      if (noEdge) {
        const noTarget = this.nodeMap.get(noEdge.target)
        if (noTarget) {
          const lbl = this.ensureLabel(noTarget)
          this.lines.push(`\tcompare VAR_RESULT, NO`)
          this.lines.push(`\tgoto_if_eq ${lbl}`)
        }
      }
      this.lines.push('\tend')

      /* emit both branches */
      for (const edge of [yesEdge, noEdge]) {
        if (edge) {
          const target = this.nodeMap.get(edge.target)
          if (target && !this.visited.has(target.id)) {
            this.lines.push('')
            const lbl = this.getLabelForNode(target)
            this.lines.push(`${lbl}:`)
            this.emitChain(target)
          }
        }
      }
    } else if (type === 'give_mon') {
      const partyEdge = outs.find((e) => e.sourceHandle === 'flow_party')
      const pcEdge = outs.find((e) => e.sourceHandle === 'flow_pc')
      const fullEdge = outs.find((e) => e.sourceHandle === 'flow_full')

      if (partyEdge) {
        const t = this.nodeMap.get(partyEdge.target)
        if (t) {
          const lbl = this.ensureLabel(t)
          this.lines.push(`\tcompare VAR_RESULT, MON_GIVEN_TO_PARTY`)
          this.lines.push(`\tgoto_if_eq ${lbl}`)
        }
      }
      if (pcEdge) {
        const t = this.nodeMap.get(pcEdge.target)
        if (t) {
          const lbl = this.ensureLabel(t)
          this.lines.push(`\tcompare VAR_RESULT, MON_GIVEN_TO_PC`)
          this.lines.push(`\tgoto_if_eq ${lbl}`)
        }
      }
      if (fullEdge) {
        const t = this.nodeMap.get(fullEdge.target)
        if (t) {
          if (!this.visited.has(t.id)) {
            this.emitChain(t)
          } else {
            this.lines.push(`\tgoto ${this.getLabelForNode(t)}`)
          }
        }
      }

      for (const edge of [partyEdge, pcEdge, fullEdge]) {
        if (edge) {
          const target = this.nodeMap.get(edge.target)
          if (target && !this.visited.has(target.id)) {
            this.lines.push('')
            const lbl = this.getLabelForNode(target)
            this.lines.push(`${lbl}:`)
            this.emitChain(target)
          }
        }
      }
    }
  }

  /* ── Helpers ── */

  private data(node: ScriptNode): ScriptNodeData {
    return node.data as unknown as ScriptNodeData
  }

  private autoLabel(): string {
    return `${this.mapName}_EventScript_${this.labelCounter++}`
  }

  private nodeLabels = new Map<string, string>()

  private ensureLabel(node: ScriptNode): string {
    if (this.nodeLabels.has(node.id)) return this.nodeLabels.get(node.id)!
    const data = this.data(node)
    if (data.schemaType === 'label' && data.labelName) {
      this.nodeLabels.set(node.id, data.labelName as string)
      return data.labelName as string
    }
    const lbl = this.autoLabel()
    this.nodeLabels.set(node.id, lbl)
    return lbl
  }

  private getLabelForNode(node: ScriptNode): string {
    return this.ensureLabel(node)
  }

  private addText(_key: string, text: string): string {
    if (!text) {
      const label = `${this.mapName}_Text_${this.textCounter++}`
      this.textLabels.set(label, '(empty)')
      return label
    }
    /* check if we already have this exact text */
    for (const [label, t] of this.textLabels) {
      if (t === text) return label
    }
    const label = `${this.mapName}_Text_${this.textCounter++}`
    this.textLabels.set(label, text)
    return label
  }

  private emitText(text: string) {
    /* split long text into lines with \n, \l, \p, $ terminators */
    const MAX_LINE = 35
    const words = text.split(/\s+/)
    let line = ''
    let lineCount = 0

    for (const word of words) {
      if (line.length + word.length + 1 > MAX_LINE && line.length > 0) {
        lineCount++
        const sep = lineCount % 2 === 0 ? '\\p' : '\\l'
        this.lines.push(`\t.string "${line}${sep}"`)
        line = word
      } else {
        line = line ? `${line} ${word}` : word
      }
    }
    if (line) {
      this.lines.push(`\t.string "${line}$"`)
    }
  }
}
