#!/usr/bin/env python3
"""
map_writer.py - Generate all files needed for a new pokeemerald map.

Takes a WFC-solved grid (or seed grid + solver) and produces:
- data/layouts/<Map>/map.bin (binary metatile grid)
- data/layouts/<Map>/border.bin (border metatiles)
- data/maps/<Map>/map.json (events, warps, metadata)
- data/maps/<Map>/scripts.inc (skeleton event scripts)
- Updates data/layouts/layouts.json with new layout entry

Usage:
    python3 map_writer.py --name MyTown --seed seed.json --music MUS_LITTLEROOT --type MAP_TYPE_TOWN
    python3 map_writer.py --name MyTown --map-bin /tmp/map.bin --width 20 --height 15 \\
        --tilesets gTileset_General gTileset_Petalburg --music MUS_LITTLEROOT
"""

import argparse
import json
import os
import struct
import sys

from maplib import (
    PROJECT_ROOT,
    load_layouts_json,
    load_metatile_attributes,
    get_behavior,
    DOOR_BEHAVIORS,
    parse_map_bin,
)

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))


def write_map_bin(packed_grid, output_path):
    """Write packed u16 grid as little-endian binary."""
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "wb") as f:
        for row in packed_grid:
            for tile in row:
                f.write(struct.pack("<H", tile))


def write_border_bin(output_path, border_metatiles=None):
    """Write border.bin — 4 u16 values (8 bytes).

    If border_metatiles not provided, uses default (metatile 1 repeated).
    """
    if border_metatiles is None:
        border_metatiles = [1, 1, 1, 1]
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "wb") as f:
        for mt in border_metatiles[:4]:
            f.write(struct.pack("<H", mt))


def find_doors_in_grid(grid, width, height, primary_attrs, secondary_attrs):
    """Scan a parsed grid for door metatiles. Returns list of (x, y)."""
    doors = []
    for y in range(height):
        for x in range(width):
            mid = grid[y][x][0]
            behavior = get_behavior(mid, primary_attrs, secondary_attrs)
            if behavior in DOOR_BEHAVIORS:
                doors.append((x, y))
    return doors


def generate_layout_entry(map_name, width, height, primary, secondary):
    """Create a layouts.json entry dict for a new map."""
    layout_name = f"{map_name}_Layout"
    layout_dir = f"data/layouts/{map_name}"
    return {
        "id": f"LAYOUT_{map_name.upper()}",
        "name": layout_name,
        "width": width,
        "height": height,
        "primary_tileset": primary,
        "secondary_tileset": secondary,
        "border_filepath": f"{layout_dir}/border.bin",
        "blockdata_filepath": f"{layout_dir}/map.bin",
    }


def generate_map_json(map_name, layout_id, doors, music="MUS_DUMMY",
                       map_type="MAP_TYPE_TOWN", weather="WEATHER_SUNNY",
                       region_map_section="MAPSEC_LITTLEROOT_TOWN"):
    """Generate map.json with auto-detected warps at door positions."""
    warp_events = []
    for i, (x, y) in enumerate(doors):
        warp_events.append({
            "x": x,
            "y": y,
            "elevation": 0,
            "dest_map": "MAP_NONE",
            "dest_warp_id": "0",
        })

    return {
        "id": f"MAP_{map_name.upper()}",
        "name": map_name,
        "layout": layout_id,
        "music": music,
        "region_map_section": region_map_section,
        "requires_flash": False,
        "weather": weather,
        "map_type": map_type,
        "allow_cycling": map_type in ("MAP_TYPE_CITY", "MAP_TYPE_TOWN", "MAP_TYPE_ROUTE"),
        "allow_escaping": False,
        "allow_running": map_type != "MAP_TYPE_INDOOR",
        "show_map_name": map_type in ("MAP_TYPE_CITY", "MAP_TYPE_TOWN", "MAP_TYPE_ROUTE"),
        "battle_scene": "MAP_BATTLE_SCENE_NORMAL",
        "connections": None,
        "object_events": [],
        "warp_events": warp_events,
        "coord_events": [],
        "bg_events": [],
    }


def generate_scripts_inc(map_name):
    """Generate a minimal skeleton scripts.inc."""
    lines = [
        f"@ Scripts for {map_name}",
        f"@ Auto-generated by map_writer.py",
        "",
    ]
    return "\n".join(lines) + "\n"


def register_in_layouts_json(entry):
    """Append a layout entry to layouts.json."""
    layouts_path = os.path.join(PROJECT_ROOT, "data", "layouts", "layouts.json")
    with open(layouts_path) as f:
        data = json.load(f)

    # Check for duplicates
    for existing in data["layouts"]:
        if existing["id"] == entry["id"]:
            print(f"Warning: layout {entry['id']} already exists, updating",
                  file=sys.stderr)
            existing.update(entry)
            with open(layouts_path, "w") as f:
                json.dump(data, f, indent=2)
                f.write("\n")
            return

    data["layouts"].append(entry)
    with open(layouts_path, "w") as f:
        json.dump(data, f, indent=2)
        f.write("\n")
    print(f"  Added {entry['id']} to layouts.json")


def full_write(map_name, width, height, primary_tileset, secondary_tileset,
               map_bin_path=None, packed_grid=None, music="MUS_DUMMY",
               map_type="MAP_TYPE_TOWN", weather="WEATHER_SUNNY",
               border_metatiles=None):
    """Orchestrate all file writes for a new map.

    Provide either map_bin_path (existing binary) or packed_grid (from WFC).
    """
    layout_dir = os.path.join(PROJECT_ROOT, "data", "layouts", map_name)
    map_dir = os.path.join(PROJECT_ROOT, "data", "maps", map_name)

    os.makedirs(layout_dir, exist_ok=True)
    os.makedirs(map_dir, exist_ok=True)

    # Write map.bin
    bin_path = os.path.join(layout_dir, "map.bin")
    if packed_grid:
        write_map_bin(packed_grid, bin_path)
        print(f"  Wrote {bin_path}")
    elif map_bin_path:
        import shutil
        shutil.copy2(map_bin_path, bin_path)
        print(f"  Copied {map_bin_path} -> {bin_path}")

    # Write border.bin
    border_path = os.path.join(layout_dir, "border.bin")
    write_border_bin(border_path, border_metatiles)
    print(f"  Wrote {border_path}")

    # Layout entry
    layout_entry = generate_layout_entry(map_name, width, height,
                                          primary_tileset, secondary_tileset)
    register_in_layouts_json(layout_entry)

    # Find doors in the grid
    primary_attrs, secondary_attrs = load_metatile_attributes(
        primary_tileset, secondary_tileset
    )
    grid = parse_map_bin(bin_path, width, height)
    doors = find_doors_in_grid(grid, width, height, primary_attrs, secondary_attrs)
    print(f"  Found {len(doors)} door(s): {doors}")

    # Write map.json
    map_json_path = os.path.join(map_dir, "map.json")
    map_data = generate_map_json(map_name, layout_entry["id"], doors,
                                  music=music, map_type=map_type, weather=weather)
    with open(map_json_path, "w") as f:
        json.dump(map_data, f, indent=2)
        f.write("\n")
    print(f"  Wrote {map_json_path}")

    # Write scripts.inc
    scripts_path = os.path.join(map_dir, "scripts.inc")
    if not os.path.exists(scripts_path):
        with open(scripts_path, "w") as f:
            f.write(generate_scripts_inc(map_name))
        print(f"  Wrote {scripts_path}")
    else:
        print(f"  Skipped {scripts_path} (already exists)")

    # Reminder of manual steps
    print()
    print("Manual steps remaining:")
    print(f"  1. Add to data/maps/map_groups.json")
    print(f"  2. Add '.include \"data/maps/{map_name}/scripts.inc\"' to data/event_scripts.s")
    print(f"  3. Update warp dest_map values in {map_json_path}")
    print(f"  4. Write NPC scripts in {scripts_path}")


def main():
    parser = argparse.ArgumentParser(
        description="Generate all files for a new pokeemerald map"
    )
    parser.add_argument("--name", required=True, help="Map name (e.g. MyNewTown)")
    parser.add_argument("--map-bin", help="Path to pre-generated map.bin")
    parser.add_argument("--seed", help="Path to seed grid JSON (runs WFC solver)")
    parser.add_argument("--width", type=int, help="Map width (required with --map-bin)")
    parser.add_argument("--height", type=int, help="Map height (required with --map-bin)")
    parser.add_argument("--tilesets", nargs=2,
                        default=["gTileset_General", "gTileset_Petalburg"],
                        help="Primary and secondary tileset labels")
    parser.add_argument("--music", default="MUS_DUMMY")
    parser.add_argument("--type", default="MAP_TYPE_TOWN",
                        dest="map_type")
    parser.add_argument("--weather", default="WEATHER_SUNNY")
    parser.add_argument("--random-seed", type=int, default=None)
    args = parser.parse_args()

    if args.seed:
        # Run WFC solver first
        import random
        if args.random_seed is not None:
            random.seed(args.random_seed)

        from wfc_solver import load_seed_grid, WFCSolver, DEFAULT_CONSTRAINTS_PATH, DEFAULT_CATALOG_PATH

        seed = load_seed_grid(args.seed)
        with open(DEFAULT_CONSTRAINTS_PATH) as f:
            constraints = json.load(f)

        catalog = {}
        if os.path.exists(DEFAULT_CATALOG_PATH):
            with open(DEFAULT_CATALOG_PATH) as f:
                catalog = json.load(f)

        primary, secondary = seed["tileset_pair"]
        tileset_key = f"{primary}+{secondary}"
        primary_attrs, secondary_attrs = load_metatile_attributes(primary, secondary)

        solver = WFCSolver(seed["width"], seed["height"], constraints,
                          tileset_key, primary_attrs, secondary_attrs)

        # Apply stamps
        for stamp_ref in seed.get("stamps", []):
            stamp_data = catalog.get("stamps", {}).get(stamp_ref["name"])
            if stamp_data:
                solver.seed_stamp(stamp_data, stamp_ref["x"], stamp_ref["y"])

        # Apply zones
        for y, row in enumerate(seed["grid"]):
            for x, zone in enumerate(row):
                if zone is not None and not solver.collapsed[y][x]:
                    solver.seed_zone(x, y, zone)

        if not solver.solve(max_backtracks=5000):
            print("Error: WFC solver failed", file=sys.stderr)
            sys.exit(1)

        elevation = seed.get("elevation_default", 3)
        packed_grid = solver.assign_collision_elevation(elevation_default=elevation)

        print(f"WFC solved: {seed['width']}x{seed['height']}")
        full_write(args.name, seed["width"], seed["height"],
                   primary, secondary, packed_grid=packed_grid,
                   music=args.music, map_type=args.map_type, weather=args.weather)

    elif args.map_bin:
        if not args.width or not args.height:
            print("Error: --width and --height required with --map-bin", file=sys.stderr)
            sys.exit(1)

        full_write(args.name, args.width, args.height,
                   args.tilesets[0], args.tilesets[1],
                   map_bin_path=args.map_bin,
                   music=args.music, map_type=args.map_type, weather=args.weather)
    else:
        print("Error: provide either --seed or --map-bin", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
